[package]
name = "plot_starter"
version = "0.34.4"
edition = "2024"
description = "A simple library to quickly plot data using `egui_plot`."
license = "MIT"
readme = "README.md"
repository = "https://github.com/bombless/plot_starter"

[dependencies]
eframe = "0.33.0"
egui_plot = "0.34.0"
